services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80

    ports:
      - "3000:80"
    
    depends_on:
      - auth-service
      - maps-service
      - mess-service
      - notifs-service
  
  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3001:80"
  
  maps-service:
    build:
      context: ./microservices/maps-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3003:80"

  mess-service:
    build:
      context: ./microservices/messages-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3004:80"
  
  notifs-service:
    build:
      context: ./microservices/notifs-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3005:80"