services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80

    ports:
      - "3000:80"

    networks:
      - custom-networks
    
    depends_on:
      - redis-data
      - auth-service
      - maps-service
      - mess-service
      - notifs-service
  
  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3001:80"
    
    networks:
      - custom-networks
    
    depends_on:
      - redis-data
  
  maps-service:
    build:
      context: ./microservices/maps-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3003:80"
    
    networks:
      - custom-networks
    
    depends_on:
      - redis-data

  mess-service:
    build:
      context: ./microservices/messages-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3004:80"
    
    networks:
      - custom-networks
    
    depends_on:
      - redis-data
  
  notifs-service:
    build:
      context: ./microservices/notifs-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=80
    
    ports:
      - "3005:80"
    
    networks:
      - custom-networks

    depends_on:
      - redis-data
  
  redis-data:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --requirepass mypassword --loglevel warning --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    
    ports:
      - "6379:6379"
    
    volumes:
      - redis-data:/data

    networks:
      - custom-networks


networks:
  custom-networks:
    driver: bridge

volumes:
  redis-data:
    driver: local